# Generated by Django 5.1.1 on 2024-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-team'], 'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-region'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='twitch_link',
            field=models.URLField(null=True, verbose_name='twitch'),
        ),
        migrations.AlterField(
            model_name='player',
            name='twitter_link',
            field=models.URLField(null=True, verbose_name='twitter'),
        ),
    ]
