# Generated by Django 5.1.1 on 2024-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0002_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='twitch_link',
            field=models.URLField(blank=True, null=True, verbose_name='twitch'),
        ),
        migrations.AlterField(
            model_name='player',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
    ]
