# Generated by Django 5.1.1 on 2024-11-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0009_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highligths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(max_length=50, verbose_name='In game name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Team name'),
        ),
        migrations.AddField(
            model_name='player',
            name='highlights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_players.highligths'),
        ),
    ]
