# Generated by Django 5.1.1 on 2024-11-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0010_highligths_alter_player_in_game_name_alter_team_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highligths',
            new_name='Highlight',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='highlights',
            new_name='highlight',
        ),
    ]
