# Generated by Django 5.1.1 on 2024-11-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0011_rename_highligths_highlight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='video_id',
            new_name='video_url',
        ),
    ]
