# Generated by Django 5.1.1 on 2024-11-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0012_rename_video_id_highlight_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='highlight',
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
