# Generated by Django 5.1.1 on 2024-11-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0014_highlight_player_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='highlight',
        ),
        migrations.AddField(
            model_name='highlight',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_players.highlight'),
        ),
    ]
