# Generated by Django 5.1.1 on 2024-11-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0015_remove_player_highlight_highlight_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_players.player'),
        ),
    ]
