# Generated by Django 5.1.1 on 2024-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0016_alter_highlight_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='video_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
