# Generated by Django 5.1.1 on 2024-11-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0017_highlight_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='youtube_API_snippet',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
