# Generated by Django 5.1.1 on 2024-11-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0019_remove_highlight_youtube_api_snippet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='snippet',
        ),
    ]
