# Generated by Django 5.1.1 on 2024-11-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0020_remove_highlight_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='video_url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
