# Generated by Django 5.1.2 on 2024-11-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0023_alter_team_options_alter_team_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_players.region', verbose_name='Region'),
        ),
    ]
