# Generated by Django 5.1.2 on 2024-11-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_players', '0028_team_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='idd',
        ),
    ]
