services:
  app:
    build: ./app
        # Запускаем сервер Gunicorn
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: web_app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static-data:/app/staticfiles
      - .:/usr/src/app/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    env_file:
      - .env
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static-data:/app/staticfiles

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - .env

  worker:
    build: 
      context: ./app
      dockerfile: Dockerfile.worker
    hostname: worker
    command: celery -A core worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - rabbitmq
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis

volumes:
  mysql-data:
  static-data:



  

