services:
  app:
    build: .
        # Запускаем сервер Gunicorn
    command: gunicorn ValorantPros.wsgi:application --bind 0.0.0.0:8000
    container_name: valorant_pros_app
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    env_file:
      - .env
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


  

